# Setup
title:               Alex Jeffery
tagline:             'Software engineer, doctor of Computer Science'
description:         'The online profile and blog of Alex Jeffery.'
url:                 https://github.com/alexj136/alexj136.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alex Jeffery
  url:               https://alexjeffery.net
  email:             apjeffery136@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
