# Setup
title:               Alex Jeffery
tagline:             'The online profile and blog of Alex Jeffery.'
url:                 https://alexjeffery.net
baseurl:             ''
paginate:            5
permalink:           pretty

include:
  - images

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
