# Setup
title:               Alex Jeffery
tagline:             ''
description:         'The online profile and blog of Alex Jeffery.'
url:                 alexjeffery.net
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alex Jeffery
  url:               alexjeffery.net

include:
  - images

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
