#!/bin/bash -xe

# Clone the site repository if it's not there
if [ ! -d target ]; then
	git clone git+ssh://git@github.com/alexj136/alexj136.github.io.git target/
fi

# Pull down the stylesheet if it's not there
if [ ! -f target/style.css ]; then
    curl -o target/style.css https://raw.githubusercontent.com/sindresorhus/github-markdown-css/1485dd78f5e744ef36e946e5ae44838e3906f9d8/github-markdown.css
fi

# Build the content
for page in pages/*; do
    outfile="target/${page##*/}.html"
    source "$page/meta.bash"
    echo "
<!DOCTYPE html>
<html>
    <head>
        <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />
        <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\" />
        <style>
            .markdown-body {
                box-sizing: border-box;
                min-width: 200px;
                max-width: 980px;
                margin: 0 auto;
                padding: 45px;
            }
            @media (max-width: 767px) {
                .markdown-body {
                    padding: 15px;
                }
            }
        </style>
        <title>$title — Alex Jeffery</title>
        <meta name=\"date\" content=\"$date\">
        <meta name=\"keywords\" content=\"$keywords\">
    </head>
    <article class=\"markdown-body\">
	$(markdown template/header.md)
    <h1>$title</h1>
	$(markdown $page/page.md)
    <p><em>Updated $date</em></p>
    </article>
</html>" > $outfile
done

for post in posts/*; do
    outfile="target/${post##*/}.html"
    source "$post/meta.bash"
    echo "
<!DOCTYPE html>
<html>
    <head>
        <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />
        <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\" />
        <style>
            .markdown-body {
                box-sizing: border-box;
                min-width: 200px;
                max-width: 980px;
                margin: 0 auto;
                padding: 45px;
            }
            @media (max-width: 767px) {
                .markdown-body {
                    padding: 15px;
                }
            }
        </style>
        <title>$title — Alex Jeffery</title>
        <meta name=\"description\" content=\"$subtitle\">
        <meta name=\"date\" content=\"$date\">
        <meta name=\"keywords\" content=\"$keywords\">
    </head>
    <article class=\"markdown-body\">
    $(markdown template/header.md)
    <h1>$title</h1>
    <p><strong>$subtitle</strong></p>
    <p><em>$date</em></p>
    $(markdown $post/page.md)
    </article>
</html>" > $outfile
    unset title subtitle date keywords todo
done

# Copy the images directory
cp -ru images target/

# Copy the extras
for file in extra/*; do
    cp -ru $file target/
done
